//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudFox.Presentation.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudFox.Presentation.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudfox is a free open source software application available under the Microsoft Public License (Ms-PL). The Author is not responsible for cost, loss of data or any harm that may be caused by usage of this softare..
        /// </summary>
        public static string ApplicationDescription {
            get {
                return ResourceManager.GetString("ApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available collections.
        /// </summary>
        public static string AvailableCollections {
            get {
                return ResourceManager.GetString("AvailableCollections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bookmarks.
        /// </summary>
        public static string Bookmarks {
            get {
                return ResourceManager.GetString("Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Weave Server....
        /// </summary>
        public static string ConnectingToWeaveServer {
            get {
                return ResourceManager.GetString("ConnectingToWeaveServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by Pieter De Rycke.
        /// </summary>
        public static string DevelopedBy {
            get {
                return ResourceManager.GetString("DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in a bug report..
        /// </summary>
        public static string FillBugReport {
            get {
                return ResourceManager.GetString("FillBugReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to folders.
        /// </summary>
        public static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to history.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have chosen to use a custom server, please provide a valid server address..
        /// </summary>
        public static string InvalidCustomServerAddress {
            get {
                return ResourceManager.GetString("InvalidCustomServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a password for your Weave account..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a sync key for your Weave account..
        /// </summary>
        public static string InvalidSyncKey {
            get {
                return ResourceManager.GetString("InvalidSyncKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide an account name for your Weave account..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known clients.
        /// </summary>
        public static string KnownClients {
            get {
                return ResourceManager.GetString("KnownClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No history is available..
        /// </summary>
        public static string NoHistoryAvailable {
            get {
                return ResourceManager.GetString("NoHistoryAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No network available..
        /// </summary>
        public static string NoNetwork {
            get {
                return ResourceManager.GetString("NoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tabs are available..
        /// </summary>
        public static string NoTabsAvailable {
            get {
                return ResourceManager.GetString("NoTabsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Website:.
        /// </summary>
        public static string ProjectWebsite {
            get {
                return ResourceManager.GetString("ProjectWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOKMARKS, HISTORY AND TABS SEARCH.
        /// </summary>
        public static string SearchDescription {
            get {
                return ResourceManager.GetString("SearchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server storage version.
        /// </summary>
        public static string ServerStorageVersion {
            get {
                return ResourceManager.GetString("ServerStorageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have trouble configuring Cloudfox, please view this guide on the Cloudfox project page:.
        /// </summary>
        public static string SetupGuideDescription {
            get {
                return ResourceManager.GetString("SetupGuideDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Guide.
        /// </summary>
        public static string SetupGuideTitle {
            get {
                return ResourceManager.GetString("SetupGuideTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How-to Setup Cloudfox.
        /// </summary>
        public static string SetupGuideUrlText {
            get {
                return ResourceManager.GetString("SetupGuideUrlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks to the following people:.
        /// </summary>
        public static string SpecialThanks {
            get {
                return ResourceManager.GetString("SpecialThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization Completed.
        /// </summary>
        public static string SynchronizationCompleted {
            get {
                return ResourceManager.GetString("SynchronizationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize Bookmarks.
        /// </summary>
        public static string SynchronizeBookmarks {
            get {
                return ResourceManager.GetString("SynchronizeBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize History.
        /// </summary>
        public static string SynchronizeHistory {
            get {
                return ResourceManager.GetString("SynchronizeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize Tabs.
        /// </summary>
        public static string SynchronizeTabs {
            get {
                return ResourceManager.GetString("SynchronizeTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Key.
        /// </summary>
        public static string SyncKey {
            get {
                return ResourceManager.GetString("SyncKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudfox requires Firefox 5.0 or higher on your pc, no additional software must be installed..
        /// </summary>
        public static string SystemRequirementsDescription {
            get {
                return ResourceManager.GetString("SystemRequirementsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Requirements.
        /// </summary>
        public static string SystemRequirementsTitle {
            get {
                return ResourceManager.GetString("SystemRequirementsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla Firefox Website.
        /// </summary>
        public static string SystemRequirementsUrlText {
            get {
                return ResourceManager.GetString("SystemRequirementsUrlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tabs.
        /// </summary>
        public static string Tabs {
            get {
                return ResourceManager.GetString("Tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t decrypt the response data from the Weave service, please verify that the entered passphrase is correct..
        /// </summary>
        public static string UnableToDecryptError {
            get {
                return ResourceManager.GetString("UnableToDecryptError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Bookmarks....
        /// </summary>
        public static string UpdatingBookmarks {
            get {
                return ResourceManager.GetString("UpdatingBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating History....
        /// </summary>
        public static string UpdatingHistory {
            get {
                return ResourceManager.GetString("UpdatingHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Profile Information....
        /// </summary>
        public static string UpdatingProfile {
            get {
                return ResourceManager.GetString("UpdatingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Tabs....
        /// </summary>
        public static string UpdatingTabs {
            get {
                return ResourceManager.GetString("UpdatingTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default server.
        /// </summary>
        public static string UseDefaultServer {
            get {
                return ResourceManager.GetString("UseDefaultServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weave node.
        /// </summary>
        public static string WeaveNode {
            get {
                return ResourceManager.GetString("WeaveNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have issues?.
        /// </summary>
        public static string YouHaveIssues {
            get {
                return ResourceManager.GetString("YouHaveIssues", resourceCulture);
            }
        }
    }
}
